name: Frontend CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: |
        cd frontend-react
        npm install

    - name: Build
      run: |
        cd frontend-react
        npm run build

    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@v2
      with:
        projectBaseDir: frontend-react
        args: >
          -Dsonar.token=7a24cfb1cb777452155d82860889060632ea548d
          -Dsonar.projectKey=Jenah_CT5192-SecureDevOps-Assignment_2_Frontend
          -Dsonar.organization=jenah
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    - name: Install ZAP CLI
      run: |
        pip install python-owasp-zap-v2.4

    - name: Run ZAP Scan
      run: |
        cd frontend-react
        npm install -g serve
        serve -s build -l 3000 &
        sleep 5
        # Run ZAP baseline scan
        python -m zapv2.baseline -t http://localhost:3000 -r zap-report.html

    - name: Upload ZAP Report
      uses: actions/upload-artifact@v4
      with:
        name: zap-report
        path: frontend-react/zap-report.html


