name: Frontend CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: |
        cd frontend-react
        npm install

    - name: Build
      run: |
        cd frontend-react
        npm run build

    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@v2
      with:
        projectBaseDir: frontend-react
        args: >
          -Dsonar.token=7a24cfb1cb777452155d82860889060632ea548d
          -Dsonar.projectKey=Jenah_CT5192-SecureDevOps-Assignment_2_Frontend
          -Dsonar.organization=jenah
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    - name: Download ZAP
      run: |
        wget https://github.com/zaproxy/zaproxy/releases/latest/download/ZAP_WEEKLY_DISTRIBUTION.zip -O zap.zip
        unzip zap.zip -d zap

    # Start ZAP in daemon mode
    - name: Start ZAP
      run: |
        java -jar zap/ZAP_2.x/zap.jar -daemon -port 8080 &
        sleep 15

    # Install Python client for ZAP
    - name: Install Python ZAP API
      run: pip install python-owasp-zap-v2.4

    # Run scan via Python API
    - name: Run ZAP Scan
      run: |
        python3 << 'EOF'
        import time
        from zapv2 import ZAPv2
        
        target = 'http://localhost:3000'
        zap = ZAPv2()
        
        print("Accessing target:", target)
        zap.urlopen(target)
        time.sleep(2)
        
        print("Spidering target...")
        zap.spider.scan(target)
        time.sleep(10)
        
        print("Running active scan...")
        zap.ascan.scan(target)
        time.sleep(10)
        
        print("Writing reports...")
        with open("frontend-react/zap-report.xml","w") as f:
            f.write(zap.core.xmlreport())
        with open("frontend-react/zap-report.html","w") as f:
            f.write(zap.core.htmlreport())
        EOF

    # Upload ZAP reports
    - name: Upload ZAP Reports
      uses: actions/upload-artifact@v4
      with:
        name: zap-reports
        path: |
          frontend-react/zap-report.xml
          frontend-react/zap-report.html

