name: Frontend CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: |
        cd frontend-react
        npm install

    - name: Build
      run: |
        cd frontend-react
        npm run build

    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@v2
      with:
        projectBaseDir: backend-flask
        args: >
          -Dsonar.token=7acbc43749f3a41de8b1402f5960573bc29889f8 
          -Dsonar.projectKey=Jenah_CT5192-SecureDevOps-Assignment_2_Backend 
          -Dsonar.organization=jenah
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}


